# ----
# Site

title: Arizona Saints Chorale
url: "https://saintschorale.org"
baseurl:
google_analytics_key: G-J4ZXPGJXMH
google_maps_javascript_api_key:
disqus_shortname:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description:  |
  A 501(c)(3) non-profit choral group motivated by a love for Jesus Christ to
  raise awareness for noble charities in our local communities.
author:
  name: Joseph Hale
  email: me@jhale.dev
  linkedin: thehale
social:
  name: Arizona Saints Chorale
  links:
    - https://www.facebook.com/Arizona-Saints-Chorale-400769617380984
    - https://www.facebook.com/100069341468507
    - https://www.youtube.com/channel/UCx0cho18Vrux7ApLNJkY8Gg
    - https://www.instagram.com/arizonasaintschorale

# -----
# Build

timezone: Etc/UTC

paginate: 10
paginate_path: "/concerts/:num/"

collections:
  staff_members:
  concerts:
    output: true
  press:
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: page
      background_image_path: /uploads/crest.png
      image: /uploads/crest.png
  -
    scope:
      path: ""
      type: "concerts"
    values:
      layout: concert
      _options:
        content:
          width: 960
          height: 2000
      _comments:
        image: Shown in social shares and the blog list.
  -
    scope:
      path: ""
      type: "press"
    values:
      layout: post
      _options:
        content:
          width: 960
          height: 2000
      _comments:
        image: Shown in social shares and the blog list.
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      _options:
        content:
          width: 960
          height: 2000
      _comments:
        image: Shown in social shares and the blog list.
  -
    scope:
      path: ""
      type: "staff_members"
    values:
      _options:
        image:
          width: 440
          height: 440

permalink: pretty

jekyll-archives:
  enabled:
    - categories

plugins:
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# -----------
# CloudCannon

_select_data:
  call_to_actions:
    - Contact
    - Learn
    - Map

  social_icons:
    - Facebook
    - Instagram
    - LinkedIn
    - Pinterest
    - Tumblr
    - Twitter
    - YouTube
    - RSS

_comments:
  large_header: Toggles the size of the top banner.
  show_in_navigation: Toggles a link in the top banner.
  author_staff_member: The staff member writing this post.
  call_to_action: Type of request shown at the bottom of this page.
  background_image_path: Image shown in the top banner, blank for the default.
  testimonials: Update, add or remove testimonials.
  map: Update the map location and display settings.
  latitude: Coordinates for the center marker on the map.
  longitude: Coordinates for the center marker on the map.
  zoom: The zoom level for the map.
  phone_extension: The digits after dialing the company phone.
  credentials: Shown as subtext on staff member summaries.
  contact_email_address: Address for the contact form to send to.
  new_window: Whether the link opens a new browser tab/window.
